controller_list:
  - name: fake_omnibase_planner_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses.
#  - group: omnibase_planner
#    pose: home

  []